apiVersion: batch/v1
kind: Job
metadata:
  name: echo
  generateName: my-test-
  annotations:
    argocd.argoproj.io/hook: PostSync
spec:
  template:
    spec:
      containers:
      - name: echo
        image: alpine
        command: ["sh",  "-c","echo this is start && date"]
      restartPolicy: Never
  backoffLimit: 4

